# Site settings
title: NorthStateFramework-csharp
email: admin@northstatesoftware.com
description: An object-oriented framework for implementing UML state machines.
short_name: NSF C#
copywrite_notice: Copyright 2014. All rights reserved.
owner: North State Software, LLC
baseurl: "/Test8"
url: "http://www.northstatesoftware.com"
twitter_username:
github_username:  NorthStateSoftware
zipball: "https://github.com/jrivenbark/Test8/zipball/master"
tarball: "https://github.com/jrivenbark/Test8/tarball/master"
repo: "https://github.com/jrivenbark/Test8"

# Build settings
markdown: kramdown
permalink: pretty
